### PR TITLE
feat(std/hash): hash lib

### PR DESCRIPTION
**Pull request by buttercubz**
continues as draft

### CODE REVIEW

**Comment by buttercubz** [comment]
In view of the desired compatibility with deno, I will port the deno hash library #66

**Comment by buttercubz** [comment]
I am working on adding AES encryption, hope to have it ready this week

**CC** @littledivy

**Comment by littledivy** [comment]
Awesome!

**Review by littledivy — APPROVED** [review]
Great work! LGTM

**Pull request merged**
