### PR TITLE
feat: add minify option to bundle cmd

### LINKED ISSUE #36: Add minification flag for `elsa bundle`
Leverage the esbuild bundle API's Minify option to produce minified output when `-m` || `--minify` is provided

### PR DESCRIPTION
**Pull request by fsmiamoto**
I've also updated some of the tests that appeared to be broken due to a rename of the testing directory.

Closes #36

### CODE REVIEW

**Comment by littledivy** [comment]
Thanks @fsmiamoto 
The broken tests are being fixed in #50

**Comment by fsmiamoto** [comment]
@littledivy  Sure! I'll remove the test changes then

**Comment by littledivy** [comment]
Thanks. I'll resolve the conflicts don't worry about it :)

**Review by littledivy — APPROVED** [review]
LGTM

**Pull request merged**
