### PR TITLE
Fix some code quality issues and add code transformer

### LINKED ISSUE #85: Mandate lint and fmt in CI

### PR DESCRIPTION
**Pull request by siddhant-deepsource**
Fixes #85

This pull request fixes some of the issues raised by [DeepSource](https://deepsource.io/gh/siddhant-deepsource/elsa) on my fork of this repo.

Some issues were automatically fixed by DeepSource, while I fixed some of them by hand.

This PR also contains a `.deepsource.toml`, in case you want to run continuous quality analyses on your repository. If you wish to do so, you can follow these steps:

* Merge this PR.
* Signup on DeepSource [here](https://deepsource.io/signup).
* Activate analysis on your repo [here](https://deepsource.io/gh/elsaland/elsa).

Adding to reporting the code quality issues, I have also added the Go (`gofmt`) and JavaScript (`Prettier`) Transformers which support auto-formatting of code on every new pull-request. You can find the transformers docs [here](https://deepsource.io/docs/transformer/).

If you don't want to use DeepSource, I can edit the PR to remove the `.deepsource.toml` file.

### CODE REVIEW

**Comment by littledivy** [comment]
Deepsource looks really nice - I'll sign up asap

**Comment by siddhant-deepsource** [comment]
Hey @littledivy 👋 Just following up, in order to activate DeepSource on this repository, you can follow these steps :

* Merge this PR.
* Signup on DeepSource here.
* Activate analysis on your repo here.

Thanks and a Happy New Year 🙂

**Comment by littledivy** [comment]
@siddhant-deepsource sorry for being super late on this, I've signed up for deepsource. Can you rerun the CI via an empty commit so it can be merged?

**Comment by siddhant-deepsource** [comment]
@littledivy Done. Please review the PR. Thanks :)

Also, thanks a lot for signing up for DeepSource 🎉 We'll try to make sure you have a great experience using it.

Thanks :)

**Pull request merged**
